"""default agent decision changed to 'pending'

Revision ID: 53ac0c265bb6
Revises: 73c9b7917da4
Create Date: 2026-06-20 01:39:34.881787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53ac0c265bb6'
down_revision: Union[str, Sequence[str], None] = '73c9b7917da4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
