"""reset_upgrade database.

Revision ID: 5afb78dedb60
Revises: 
Create Date: 2026-06-14 22:35:46.297241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5afb78dedb60'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('policy_limit', sa.Float(), nullable=False),
    sa.Column('risk_tier', sa.String(), nullable=False),
    sa.Column('manager_slack_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expense_policies',
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('max_amount', sa.Float(), nullable=False),
    sa.Column('requires_receipt', sa.Boolean(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('category')
    )
    op.create_table('transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('merchant', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('receipt_provided', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['category'], ['expense_policies.category'], name='fk_transaction_category'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='fk_transaction_employee'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('idx_trans_emp_date', ['employee_id', 'date'], unique=False)

    op.create_table('investigations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('decision', sa.String(), nullable=True),
    sa.Column('reasoning', sa.String(), nullable=True),
    sa.Column('evidence_summary', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category'], ['expense_policies.category'], name='fk_investigations_category'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='fk_investigations_employee'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name='fk_investigation_transaction'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.create_index('idx_inv_employee_id', ['employee_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.drop_index('idx_inv_employee_id')

    op.drop_table('investigations')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('idx_trans_emp_date')

    op.drop_table('transactions')
    op.drop_table('expense_policies')
    op.drop_table('employees')
    # ### end Alembic commands ###
