"""update foreign keys

Revision ID: ba5af12d2e56
Revises: ea960c1bf822
Create Date: 2026-06-10 11:05:42.414189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba5af12d2e56'
down_revision: Union[str, Sequence[str], None] = 'ea960c1bf822'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_investigations_employee', 'employees', ['employee_id'], ['id'])
        batch_op.create_foreign_key('fk_investigations_category', 'expense_policies', ['category'], ['category'])

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_transaction_category', 'expense_policies', ['category'], ['category'])
        batch_op.create_foreign_key('fk_transaction_employee', 'employees', ['employee_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transaction_employee', type_='foreignkey')
        batch_op.drop_constraint('fk_transaction_category', type_='foreignkey')

    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_investigations_category', type_='foreignkey')
        batch_op.drop_constraint('fk_investigations_employee', type_='foreignkey')

    # ### end Alembic commands ###
