"""data upgrades transactions

Revision ID: c87d7755382a
Revises: 98d303cc87a6
Create Date: 2026-06-20 02:30:16.263177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c87d7755382a'
down_revision: Union[str, Sequence[str], None] = '98d303cc87a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # status data into transaction_status
    op.execute("update transactions set transaction_status = status")
    # drop status field
    op.drop_column("transactions", "status")
    # to add check constraints
    op.execute("""Create table if not exists transactions_new
    ( id VARCHAR PRIMARY KEY,
    employee_id VARCHAR NOT NULL,
    date DATETIME,
    category VARCHAR NOT NULL,
    amount FLOAT NOT NULL,
    merchant VARCHAR,
    receipt_provided BOOLEAN,
    transaction_status VARCHAR,
    agent_decision VARCHAR,
    HIL_status VARCHAR,
    CONSTRAINT fk_transaction_employee FOREIGN KEY (employee_id) REFERENCES employee(id),
    CONSTRAINT fk_transaction_category FOREIGN KEY (category) REFERENCES expense_policies(category),
    CHECK (transaction_status in ('completed','flagged', 'pending_review','cancelled','failed')),
    CHECK (agent_decision in ('pending','approved', 'rejected', 'escalated')),
    CHECK (HIL_status is NULL or HIL_status in ('approved','rejected')))
    """)

    op.execute("""
        INSERT INTO transactions_new 
            (id, employee_id, date, category, amount, merchant, receipt_provided, transaction_status, agent_decision)
        SELECT 
            id, employee_id, date, category, amount, merchant, receipt_provided, transaction_status, agent_decision
        FROM transactions
    """)

    op.execute("DROP TABLE transactions")
    op.execute("ALTER TABLE transactions_new rename to transactions")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    op.execute("""Create table if not exists transactions_old (
        id VARCHAR PRIMARY KEY,
        employee_id VARCHAR NOT NULL,
        date DATETIME,
        category VARCHAR NOT NULL,
        amount FLOAT NOT NULL,
        merchant VARCHAR,
        receipt_provided BOOLEAN,
        status VARCHAR,
        agent_decision VARCHAR,
        HIL_status VARCHAR,
        transaction_status VARCHAR,
        CONSTRAINT fk_transaction_employee FOREIGN KEY (employee_id) REFERENCES employee(id),
        CONSTRAINT fk_transaction_category FOREIGN KEY (category) REFERENCES expense_policies(category))
        """)

    op.execute("""
        INSERT INTO transactions_old 
            (id, employee_id, date, category, amount, merchant, receipt_provided, status, agent_decision,
            HIL_status)
        SELECT 
            id, employee_id, date, category, amount, merchant, receipt_provided, transaction_status, agent_decision,
            HIL_status FROM transactions
    """)
    op.execute("UPDATE transactions_old set transaction_status = 'flagged'")
    op.execute("DROP TABLE transactions")
    op.execute("ALTER TABLE transactions_old RENAME TO transactions")
    # ### end Alembic commands ###
