"""in investigations table - decision to agent_decision

Revision ID: dea7d340bdbe
Revises: 9268a5771bb1
Create Date: 2026-06-21 01:16:01.092653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dea7d340bdbe'
down_revision: Union[str, Sequence[str], None] = '9268a5771bb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agent_decision', sa.String(), nullable=True))
        batch_op.drop_column('decision')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('decision', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('agent_decision')

    # ### end Alembic commands ###
