"""add relationships and indexes

Revision ID: ea960c1bf822
Revises: 5a6c987c3753
Create Date: 2026-06-10 10:45:46.343919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea960c1bf822'
down_revision: Union[str, Sequence[str], None] = '5a6c987c3753'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.create_index('idx_inv_employee_id', ['employee_id'], unique=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('idx_trans_emp_date', ['employee_id', 'date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('idx_trans_emp_date')

    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.drop_index('idx_inv_employee_id')

    # ### end Alembic commands ###
